version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  #networks:
  #  - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  #volumes:
  #  - rabbitmq_data:/var/lib/rabbitmq
  #networks:
  #  - app_network

  gateway:
    build: 
      context: .
      dockerfile: ./services/gateway/Dockerfile
    container_name: gateway_container
    ports:
      - "3000:3000"
    depends_on:
      - packages_service

  packages_service:
    build:
      context: .
      dockerfile: ./services/packages/Dockerfile 
    container_name: packages_service_container
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  
  location_service:
    build:
      context: .
      dockerfile: ./services/locations/Dockerfile 
    container_name: location_service_container
    ports:
      - "3004:3004"
    depends_on:
      - mongo
      - rabbitmq

  socket_service:
    build: 
      context: .
      dockerfile: ./services/socket/Dockerfile
    container_name: socket_service_container
    #environment:
    #  - RABBITMQ_URL=amqp://admin:admin@rabbitmq_container
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq

  frontend:
    build: 
      context: .
      dockerfile: ./services/frontend/Dockerfile
    container_name: frontend_container
    ports:
      - "8080:80"
    depends_on:
      - gateway
      - packages_service
      - location_service
      - socket_service
volumes:
  mongo_data:
